/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/customer/account": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Provision the authenticated customer account */
        readonly post: operations["provisionCustomerAccount"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/context": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Resolve the caller's current staff scope */
        readonly get: operations["getStaffContext"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/menu": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load the configured guest menu */
        readonly get: operations["getCurrentGuestMenu"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/menu/products/{productSlug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a product from the configured guest menu */
        readonly get: operations["getCurrentGuestProduct"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/locations/{locationSlug}/menu": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a guest menu by location */
        readonly get: operations["getGuestLocationMenu"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/locations/{locationSlug}/menu/products/{productSlug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a guest product by location */
        readonly get: operations["getGuestLocationProduct"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly ProblemDetail: {
            /** Format: uri */
            readonly type: string;
            readonly title: string;
            /** Format: int32 */
            readonly status: number;
            readonly detail: string;
            /** Format: uri */
            readonly instance: string;
            readonly properties: {
                readonly [key: string]: unknown;
            };
        };
        readonly CustomerAccountDto: {
            /** Format: uuid */
            readonly id: string;
            readonly email: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly StaffContext: {
            /** Format: uuid */
            readonly accountId: string;
            readonly memberships: readonly components["schemas"]["StaffMembership"][];
        };
        readonly StaffLocation: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly timezone: string;
            readonly defaultLocale: string;
            readonly currencyCode: string;
        };
        readonly StaffMembership: {
            /** Format: uuid */
            readonly organizationId: string;
            readonly organizationName: string;
            /** @enum {string} */
            readonly role: "OWNER" | "MANAGER";
            readonly locations: readonly components["schemas"]["StaffLocation"][];
        };
        readonly Location: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly currency: string;
        };
        readonly Menu: {
            readonly location: components["schemas"]["Location"];
            readonly products: readonly components["schemas"]["ProductSummary"][];
        };
        readonly Money: {
            /** Format: int64 */
            readonly amountMinor: number;
            readonly currency: string;
        };
        readonly ProductSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly description: string;
            readonly category: string;
            readonly artworkKey: string;
            readonly startingPrice: components["schemas"]["Money"];
            readonly available: boolean;
        };
        readonly OptionChoice: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly isDefault: boolean;
            readonly priceDelta: components["schemas"]["Money"];
        };
        readonly OptionGroup: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly minimumSelections: number;
            /** Format: int32 */
            readonly maximumSelections: number;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly choices: readonly components["schemas"]["OptionChoice"][];
        };
        readonly Product: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly description: string;
            readonly category: string;
            readonly artworkKey: string;
            readonly variants: readonly components["schemas"]["Variant"][];
        };
        readonly Variant: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly isDefault: boolean;
            readonly available: boolean;
            readonly price: components["schemas"]["Money"];
            readonly optionGroups: readonly components["schemas"]["OptionGroup"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly provisionCustomerAccount: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Existing customer account */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CustomerAccountDto"];
                };
            };
            /** @description Customer account created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CustomerAccountDto"];
                };
            };
            /** @description Invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Customer account disabled */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getStaffContext: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current active staff scope */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StaffContext"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active staff access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getCurrentGuestMenu: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current guest menu */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Menu"];
                };
            };
            /** @description Configured catalog resource unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getCurrentGuestProduct: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly productSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest product configuration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Catalog product unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getGuestLocationMenu: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly locationSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest location menu */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Menu"];
                };
            };
            /** @description Catalog location unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getGuestLocationProduct: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly locationSlug: string;
                readonly productSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest product configuration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Catalog product unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
