/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get recipe metadata and version history */
        readonly get: operations["getRecipe"];
        /** Update active recipe metadata */
        readonly put: operations["updateRecipe"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}/versions/{versionId}/draft": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Replace a draft formula atomically */
        readonly put: operations["replaceRecipeDraft"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/ingredients/{ingredientId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Update an active ingredient */
        readonly put: operations["updateIngredient"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List recipes in an authorized organization */
        readonly get: operations["listRecipes"];
        readonly put?: never;
        /** Create a recipe with an empty draft */
        readonly post: operations["createRecipe"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}/versions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create the next recipe draft */
        readonly post: operations["createRecipeVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}/versions/{versionId}/retire": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Retire an unused published version */
        readonly post: operations["retireRecipeVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}/versions/{versionId}/publish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Publish and freeze a recipe draft */
        readonly post: operations["publishRecipeVersion"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/recipes/{recipeId}/archive": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Archive an unused recipe */
        readonly post: operations["archiveRecipe"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/ingredients": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List ingredients in an authorized organization */
        readonly get: operations["listIngredients"];
        readonly put?: never;
        /** Create an ingredient */
        readonly post: operations["createIngredient"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/organizations/{organizationId}/ingredients/{ingredientId}/archive": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Archive an ingredient */
        readonly post: operations["archiveIngredient"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/customer/account": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Provision the authenticated customer account */
        readonly post: operations["provisionCustomerAccount"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/staff/context": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Resolve the caller's current staff scope */
        readonly get: operations["getStaffContext"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/menu": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load the configured guest menu */
        readonly get: operations["getCurrentGuestMenu"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/menu/products/{productSlug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a product from the configured guest menu */
        readonly get: operations["getCurrentGuestProduct"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/locations/{locationSlug}/menu": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a guest menu by location */
        readonly get: operations["getGuestLocationMenu"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/guest/locations/{locationSlug}/menu/products/{productSlug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Load a guest product by location */
        readonly get: operations["getGuestLocationProduct"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly ProblemDetail: {
            /** Format: uri */
            readonly type: string;
            readonly title: string;
            /** Format: int32 */
            readonly status: number;
            readonly detail: string;
            /** Format: uri */
            readonly instance: string;
            readonly properties: {
                readonly [key: string]: unknown;
            };
        };
        readonly UpdateRecipeRequest: {
            readonly name: string;
            readonly description?: string | null;
            /** Format: int64 */
            readonly version: number;
        };
        readonly RecipeComponent: {
            /** Format: uuid */
            readonly ingredientId: string;
            readonly ingredientName: string;
            /** @enum {string} */
            readonly baseUnit: "GRAM" | "MILLILITER" | "EACH";
            readonly quantity: string;
        };
        readonly RecipeDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly description: string | null;
            /** Format: int64 */
            readonly version: number;
            readonly archived: boolean;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            readonly versions: readonly components["schemas"]["RecipeVersion"][];
        };
        readonly RecipeVersion: {
            /** Format: uuid */
            readonly id: string;
            /** Format: int32 */
            readonly versionNumber: number;
            /** @enum {string} */
            readonly status: "DRAFT" | "PUBLISHED" | "RETIRED";
            /** Format: int64 */
            readonly version: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly publishedAt: string | null;
            readonly components: readonly components["schemas"]["RecipeComponent"][];
        };
        readonly ComponentRequest: {
            /** Format: uuid */
            readonly ingredientId: string;
            readonly quantity: string;
        };
        readonly UpdateDraftRequest: {
            /** Format: int64 */
            readonly version: number;
            readonly components: readonly components["schemas"]["ComponentRequest"][];
        };
        readonly UpdateIngredientRequest: {
            readonly name: string;
            readonly sku?: string | null;
            readonly reorderThreshold?: string | null;
            /** Format: int64 */
            readonly version: number;
        };
        readonly Ingredient: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly sku: string | null;
            /** @enum {string} */
            readonly baseUnit: "GRAM" | "MILLILITER" | "EACH";
            readonly reorderThreshold: string | null;
            /** Format: int64 */
            readonly version: number;
            readonly archived: boolean;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        readonly CreateRecipeRequest: {
            readonly name: string;
            readonly description?: string | null;
        };
        readonly CreateVersionRequest: {
            /** Format: int64 */
            readonly version: number;
            /** Format: uuid */
            readonly sourceVersionId?: string | null;
        };
        readonly VersionRequest: {
            /** Format: int64 */
            readonly version: number;
        };
        readonly CreateIngredientRequest: {
            readonly name: string;
            readonly sku?: string | null;
            /** @enum {string} */
            readonly baseUnit: "GRAM" | "MILLILITER" | "EACH";
            readonly reorderThreshold?: string | null;
        };
        readonly ArchiveIngredientRequest: {
            /** Format: int64 */
            readonly version: number;
        };
        readonly CustomerAccountDto: {
            /** Format: uuid */
            readonly id: string;
            readonly email: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly RecipePage: {
            readonly items: readonly components["schemas"]["RecipeSummary"][];
            /** Format: int32 */
            readonly page: number;
            /** Format: int32 */
            readonly size: number;
            /** Format: int64 */
            readonly totalItems: number;
            /** Format: int64 */
            readonly totalPages: number;
        };
        readonly RecipeSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly description: string | null;
            /** Format: int64 */
            readonly version: number;
            readonly archived: boolean;
            /** Format: int32 */
            readonly latestVersionNumber: number;
            readonly latestStatus: string;
        };
        readonly IngredientPage: {
            readonly items: readonly components["schemas"]["Ingredient"][];
            /** Format: int32 */
            readonly page: number;
            /** Format: int32 */
            readonly size: number;
            /** Format: int64 */
            readonly totalItems: number;
            /** Format: int64 */
            readonly totalPages: number;
        };
        readonly StaffContext: {
            /** Format: uuid */
            readonly accountId: string;
            readonly memberships: readonly components["schemas"]["StaffMembership"][];
        };
        readonly StaffLocation: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly timezone: string;
            readonly defaultLocale: string;
            readonly currencyCode: string;
        };
        readonly StaffMembership: {
            /** Format: uuid */
            readonly organizationId: string;
            readonly organizationName: string;
            /** @enum {string} */
            readonly role: "OWNER" | "MANAGER";
            readonly locations: readonly components["schemas"]["StaffLocation"][];
        };
        readonly Location: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly currency: string;
        };
        readonly Menu: {
            readonly location: components["schemas"]["Location"];
            readonly products: readonly components["schemas"]["ProductSummary"][];
        };
        readonly Money: {
            /** Format: int64 */
            readonly amountMinor: number;
            readonly currency: string;
        };
        readonly ProductSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly description: string;
            readonly category: string;
            readonly artworkKey: string;
            readonly startingPrice: components["schemas"]["Money"];
            readonly available: boolean;
        };
        readonly OptionChoice: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly isDefault: boolean;
            readonly priceDelta: components["schemas"]["Money"];
        };
        readonly OptionGroup: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly minimumSelections: number;
            /** Format: int32 */
            readonly maximumSelections: number;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly choices: readonly components["schemas"]["OptionChoice"][];
        };
        readonly Product: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly description: string;
            readonly category: string;
            readonly artworkKey: string;
            readonly variants: readonly components["schemas"]["Variant"][];
        };
        readonly Variant: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            /** Format: int32 */
            readonly displayOrder: number;
            readonly isDefault: boolean;
            readonly available: boolean;
            readonly price: components["schemas"]["Money"];
            readonly optionGroups: readonly components["schemas"]["OptionGroup"][];
        };
    };
    responses: {
        /** @description Problem details */
        readonly Problem: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getRecipe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Recipe detail */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeDetail"];
                };
            };
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
        };
    };
    readonly updateRecipe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateRecipeRequest"];
            };
        };
        readonly responses: {
            /** @description Recipe updated */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeDetail"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly replaceRecipeDraft: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
                readonly versionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateDraftRequest"];
            };
        };
        readonly responses: {
            /** @description Draft formula replaced */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeVersion"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly updateIngredient: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly ingredientId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UpdateIngredientRequest"];
            };
        };
        readonly responses: {
            /** @description Ingredient updated */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ingredient"];
                };
            };
            /** @description Invalid ingredient input */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active catalog access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ingredient not found in this organization */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ingredient conflict or stale version */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly listRecipes: {
        readonly parameters: {
            readonly query?: {
                readonly page?: number;
                readonly size?: number;
                readonly query?: string;
                readonly includeArchived?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Recipe page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipePage"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
        };
    };
    readonly createRecipe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateRecipeRequest"];
            };
        };
        readonly responses: {
            /** @description Recipe created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeDetail"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly createRecipeVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateVersionRequest"];
            };
        };
        readonly responses: {
            /** @description Draft version created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeVersion"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly retireRecipeVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
                readonly versionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionRequest"];
            };
        };
        readonly responses: {
            /** @description Recipe version retired */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeVersion"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly publishRecipeVersion: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
                readonly versionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionRequest"];
            };
        };
        readonly responses: {
            /** @description Recipe version published */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeVersion"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly archiveRecipe: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly recipeId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionRequest"];
            };
        };
        readonly responses: {
            /** @description Recipe archived or already archived */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "*/*": components["schemas"]["RecipeDetail"];
                };
            };
            readonly 400: components["responses"]["Problem"];
            readonly 401: components["responses"]["Problem"];
            readonly 403: components["responses"]["Problem"];
            readonly 404: components["responses"]["Problem"];
            readonly 409: components["responses"]["Problem"];
        };
    };
    readonly listIngredients: {
        readonly parameters: {
            readonly query?: {
                readonly page?: number;
                readonly size?: number;
                readonly query?: string;
                readonly includeArchived?: boolean;
            };
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Ingredient page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IngredientPage"];
                };
            };
            /** @description Invalid pagination or search input */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active catalog access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly createIngredient: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateIngredientRequest"];
            };
        };
        readonly responses: {
            /** @description Ingredient created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ingredient"];
                };
            };
            /** @description Invalid ingredient input */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active catalog access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ingredient name or SKU already exists */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly archiveIngredient: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly organizationId: string;
                readonly ingredientId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ArchiveIngredientRequest"];
            };
        };
        readonly responses: {
            /** @description Ingredient archived or already archived */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Ingredient"];
                };
            };
            /** @description Invalid version */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active catalog access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ingredient not found in this organization */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Ingredient version is stale */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly provisionCustomerAccount: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Existing customer account */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CustomerAccountDto"];
                };
            };
            /** @description Customer account created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CustomerAccountDto"];
                };
            };
            /** @description Invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Customer account disabled */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getStaffContext: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current active staff scope */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StaffContext"];
                };
            };
            /** @description Missing or invalid authenticated identity */
            readonly 401: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No active staff access */
            readonly 403: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getCurrentGuestMenu: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current guest menu */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Menu"];
                };
            };
            /** @description Configured catalog resource unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getCurrentGuestProduct: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly productSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest product configuration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Catalog product unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getGuestLocationMenu: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly locationSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest location menu */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Menu"];
                };
            };
            /** @description Catalog location unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    readonly getGuestLocationProduct: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly locationSlug: string;
                readonly productSlug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Guest product configuration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Catalog product unavailable */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
