_format_version: "3.0"
_transform: true

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-v1
        paths:
          - /auth/v1
        strip_path: true

plugins:
  - name: cors
    route: auth-v1
    config:
      origins:
        - http://localhost:4173
        - http://localhost:5173
      methods:
        - GET
        - POST
        - OPTIONS
      headers:
        - authorization
        - apikey
        - content-type
        - x-client-info
        - x-supabase-api-version
      max_age: 3600
