import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

test("owner creates a MYR shop and configures explicit add-on prices", async ({ page }, testInfo) => {
  await page.goto("/staff/sign-in");
  await page.getByLabel("Email address").fill("owner@owner.com");
  await page.getByLabel("Password", { exact: true }).fill("Owner@1234");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Operations overview" })).toBeVisible();
  await page.goto("/staff/locations");
  const name = `Currency check ${Date.now()}`;
  const slug = `currency-check-${Date.now()}`;
  await page.getByLabel("Shop name").fill(name);
  await page.getByLabel("Public shop URL").fill(slug);
  await page.getByRole("combobox", { name: "Settlement currency" }).click();
  await page.getByRole("option", { name: "MYR", exact: true }).click();
  await page.getByRole("combobox", { name: "Shop timezone" }).click();
  await page.getByRole("option", { name: "Asia/Kuala_Lumpur", exact: true }).click();
  await page.getByRole("button", { name: "Create shop", exact: true }).click();
  await expect(page.getByText(`${name} created.`, { exact: false })).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("owner-currency.png"), fullPage: true });
  await page.goto("/staff/catalog/menu");
  const row = page.getByRole("row").filter({ hasText: "Moonlit Milk Tea" });
  await row.getByRole("link", { name: "Open product" }).click();
  const variant = page.locator("article.menu-variant-card").filter({ has: page.getByRole("heading", { name: "Medium", exact: true }) });
  await variant.getByRole("button", { name: "Set currency prices" }).click();
  await variant.getByRole("combobox", { name: "Price currency" }).click();
  await page.getByRole("option", { name: "MYR", exact: true }).click();
  await expect(variant.getByLabel("Toppings · Pearls (MYR)")).toBeVisible();
  for (const input of await variant.locator('input[id^="currency-price-"]').all()) await input.fill("0.00");
  await variant.getByLabel("Toppings · Pearls (MYR)").fill("1.50");
  const saved = page.waitForResponse((response) => response.url().includes("/currency-prices/MYR") && response.request().method() === "PUT" && response.status() === 200);
  await variant.getByRole("button", { name: "Save currency prices" }).click();
  await saved;
  const offering = variant.locator(".menu-location-card").filter({ hasText: name });
  await offering.getByRole("button", { name: "Add offering" }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("combobox", { name: "Published recipe" }).click();
  await page.getByRole("option", { name: "Moonlit Milk Tea · v1", exact: true }).click();
  await dialog.getByLabel("Price (MYR minor units)").fill("1000");
  await dialog.getByRole("checkbox", { name: "Available to guests" }).check();
  await dialog.getByRole("button", { name: "Save offering" }).click();
  await expect(dialog).not.toBeVisible();
  await page.goto(`/shop/${slug}`);
  await page.getByRole("link", { name: /Customize Moonlit Milk Tea/ }).click();
  await page.getByRole("checkbox", { name: /Pearls/ }).check();
  await expect(page.getByRole("button", { name: /Add to order/ })).toContainText("11.50");
  await page.getByRole("button", { name: /Add to order/ }).click();
  await page.getByRole("link", { name: "View order" }).click();
  await page.getByRole("button", { name: /Place order ·/ }).click();
  await expect(page.getByRole("heading", { name: /Pickup BT/ })).toBeVisible();
  await expect(page.getByText("Confirmed total").locator("..")).toContainText("11.50");
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
});
